# Generated by Django 5.1.6 on 2025-04-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskdetail_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_completed',
        ),
    ]
