# Generated by Django 5.1.6 on 2025-04-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tasks_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
    ]
