# Generated by Django 5.1.5 on 2025-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employee_tasks_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
