# Generated by Django 5.1.6 on 2025-04-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
